# Generated by Django 2.2.13 on 2020-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('timestamp', models.IntegerField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
